refactor: update dev test - competly refactor

diff --git a/scripts/bin/update-packages b/scripts/bin/update-packages
--- a/scripts/bin/update-packages
+++ b/scripts/bin/update-packages
@@ -10,70 +10,70 @@ set -u
 # Push changes to remote.
 : "${GIT_PUSH_PACKAGES:=false}"
 
-export TERMUX_PKG_UPDATE_METHOD=""             # Which method to use for updating? (repology, github or gitlab)
-export TERMUX_PKG_UPDATE_TAG_TYPE=""           # Whether to use latest-release-tag or newest-tag.
-export TERMUX_GITLAB_API_HOST="gitlab.com"     # Default host for gitlab-ci.
-export TERMUX_PKG_AUTO_UPDATE=false            # Whether to auto-update or not. Disabled by default.
-export TERMUX_PKG_UPDATE_VERSION_REGEXP=""     # Regexp to extract version with `grep -oP`.
-export TERMUX_PKG_UPDATE_VERSION_SED_REGEXP="" # Regexp to extract version with `sed`.
-export TERMUX_REPOLOGY_DATA_FILE
-TERMUX_REPOLOGY_DATA_FILE="$(mktemp -t termux-repology.XXXXXX)" # File to store repology data.
+export NEOTERM_PKG_UPDATE_METHOD=""             # Which method to use for updating? (repology, github or gitlab)
+export NEOTERM_PKG_UPDATE_TAG_TYPE=""           # Whether to use latest-release-tag or newest-tag.
+export NEOTERM_GITLAB_API_HOST="gitlab.com"     # Default host for gitlab-ci.
+export NEOTERM_PKG_AUTO_UPDATE=false            # Whether to auto-update or not. Disabled by default.
+export NEOTERM_PKG_UPDATE_VERSION_REGEXP=""     # Regexp to extract version with `grep -oP`.
+export NEOTERM_PKG_UPDATE_VERSION_SED_REGEXP="" # Regexp to extract version with `sed`.
+export NEOTERM_REPOLOGY_DATA_FILE
+NEOTERM_REPOLOGY_DATA_FILE="$(mktemp -t neoterm-repology.XXXXXX)" # File to store repology data.
 
-export TERMUX_SCRIPTDIR
-TERMUX_SCRIPTDIR=$(realpath "$(dirname "$0")/../..") # Root of repository.
+export NEOTERM_SCRIPTDIR
+NEOTERM_SCRIPTDIR=$(realpath "$(dirname "$0")/../..") # Root of repository.
 
-export TERMUX_PACKAGES_DIRECTORIES
-TERMUX_PACKAGES_DIRECTORIES=$(jq --raw-output 'del(.pkg_format) | keys | .[]' "${TERMUX_SCRIPTDIR}"/repo.json)
+export NEOTERM_PACKAGES_DIRECTORIES
+NEOTERM_PACKAGES_DIRECTORIES=$(jq --raw-output 'del(.pkg_format) | keys | .[]' "${NEOTERM_SCRIPTDIR}"/repo.json)
 
 # Define few more variables used by scripts.
 # shellcheck source=scripts/properties.sh
-. "${TERMUX_SCRIPTDIR}/scripts/properties.sh"
+. "${NEOTERM_SCRIPTDIR}/scripts/properties.sh"
 
 # Utility function to write error message to stderr.
-# shellcheck source=scripts/updates/utils/termux_error_exit.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/utils/termux_error_exit.sh
+# shellcheck source=scripts/updates/utils/neoterm_error_exit.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/utils/neoterm_error_exit.sh
 
 # Utility function to write updated version to build.sh.
-# shellcheck source=scripts/updates/utils/termux_pkg_upgrade_version.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/utils/termux_pkg_upgrade_version.sh
+# shellcheck source=scripts/updates/utils/neoterm_pkg_upgrade_version.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/utils/neoterm_pkg_upgrade_version.sh
 
 # Utility function to check if package needs to be updated, based on version comparison.
-# shellcheck source=scripts/updates/utils/termux_pkg_is_update_needed.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/utils/termux_pkg_is_update_needed.sh
+# shellcheck source=scripts/updates/utils/neoterm_pkg_is_update_needed.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/utils/neoterm_pkg_is_update_needed.sh
 
 # Wrapper around github api to get latest release or newest tag.
-# shellcheck source=scripts/updates/api/termux_github_api_get_tag.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/api/termux_github_api_get_tag.sh
+# shellcheck source=scripts/updates/api/neoterm_github_api_get_tag.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/api/neoterm_github_api_get_tag.sh
 
 # Wrapper around gitlab api to get latest release or newest tag.
-# shellcheck source=scripts/updates/api/termux_gitlab_api_get_tag.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/api/termux_gitlab_api_get_tag.sh
+# shellcheck source=scripts/updates/api/neoterm_gitlab_api_get_tag.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/api/neoterm_gitlab_api_get_tag.sh
 
 # Function to get latest version of a package as per repology.
-# shellcheck source=scripts/updates/api/termux_repology_api_get_latest_version.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/api/termux_repology_api_get_latest_version.sh
+# shellcheck source=scripts/updates/api/neoterm_repology_api_get_latest_version.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/api/neoterm_repology_api_get_latest_version.sh
 
 # Default auto update script for packages hosted on github.com. Should not be overrided by build.sh.
-# To use custom algorithm, one should override termux_pkg_auto_update().
-# shellcheck source=scripts/updates/internal/termux_github_auto_update.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/internal/termux_github_auto_update.sh
+# To use custom algorithm, one should override neoterm_pkg_auto_update().
+# shellcheck source=scripts/updates/internal/neoterm_github_auto_update.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/internal/neoterm_github_auto_update.sh
 
 # Default auto update script for packages hosted on hosts using gitlab-ci. Should not be overrided by build.sh.
-# To use custom algorithm, one should override termux_pkg_auto_update().
-# shellcheck source=scripts/updates/internal/termux_gitlab_auto_update.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/internal/termux_gitlab_auto_update.sh
+# To use custom algorithm, one should override neoterm_pkg_auto_update().
+# shellcheck source=scripts/updates/internal/neoterm_gitlab_auto_update.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/internal/neoterm_gitlab_auto_update.sh
 
 # Default auto update script for rest packages. Should not be overrided by build.sh.
-# To use custom algorithm, one should override termux_pkg_auto_update().
-# shellcheck source=scripts/updates/internal/termux_repology_auto_update.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/internal/termux_repology_auto_update.sh
+# To use custom algorithm, one should override neoterm_pkg_auto_update().
+# shellcheck source=scripts/updates/internal/neoterm_repology_auto_update.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/internal/neoterm_repology_auto_update.sh
 
 # Main script to:
 # - by default, decide which update method to use,
 # - but can be overrided by build.sh to use custom update method.
 # - For example: see neovim-nightly's build.sh.
-# shellcheck source=scripts/updates/termux_pkg_auto_update.sh
-. "${TERMUX_SCRIPTDIR}"/scripts/updates/termux_pkg_auto_update.sh
+# shellcheck source=scripts/updates/neoterm_pkg_auto_update.sh
+. "${NEOTERM_SCRIPTDIR}"/scripts/updates/neoterm_pkg_auto_update.sh
 
 # Converts milliseconds to human-readable format. 
 # Example: `ms_to_human_readable 123456789` => 34h 17m 36s 789ms
@@ -93,17 +93,17 @@ quiet() {
 }
 
 _update() {
-	export TERMUX_PKG_NAME
-	TERMUX_PKG_NAME="$(basename "$1")"
-	export TERMUX_PKG_BUILDER_DIR
-	TERMUX_PKG_BUILDER_DIR="$(realpath "$1")" # Directory containing build.sh.
+	export NEOTERM_PKG_NAME
+	NEOTERM_PKG_NAME="$(basename "$1")"
+	export NEOTERM_PKG_BUILDER_DIR
+	NEOTERM_PKG_BUILDER_DIR="$(realpath "$1")" # Directory containing build.sh.
 
-	IFS="," read -r -a BLACKLISTED_ARCH <<<"${TERMUX_PKG_BLACKLISTED_ARCHES:-}"
-	export TERMUX_ARCH="" # Arch to test updates.
+	IFS="," read -r -a BLACKLISTED_ARCH <<<"${NEOTERM_PKG_BLACKLISTED_ARCHES:-}"
+	export NEOTERM_ARCH="" # Arch to test updates.
 	for arch in aarch64 arm i686 x86_64; do
 		# shellcheck disable=SC2076
 		if [[ ! " ${BLACKLISTED_ARCH[*]} " =~ " ${arch} " ]]; then
-			TERMUX_ARCH="${arch}"
+			NEOTERM_ARCH="${arch}"
 			break
 		fi
 	done
@@ -112,22 +112,22 @@ _update() {
 	# - error on unbound variable. (All global variables used should be covered by properties.sh and above.)
 	set +e +u
 	# shellcheck source=/dev/null
-	. "${TERMUX_PKG_BUILDER_DIR}"/build.sh 2>/dev/null
+	. "${NEOTERM_PKG_BUILDER_DIR}"/build.sh 2>/dev/null
 	set -e -u
 
 	echo # Newline.
-	echo "INFO: Updating ${TERMUX_PKG_NAME} [Current version: ${TERMUX_PKG_VERSION}]"
-	termux_pkg_auto_update
+	echo "INFO: Updating ${NEOTERM_PKG_NAME} [Current version: ${NEOTERM_PKG_VERSION}]"
+	neoterm_pkg_auto_update
 }
 
 declare -A _LATEST_TAGS=()
 declare -A _FAILED_UPDATES=()
 declare -a _ALREADY_SEEN=() # Array of packages successfully updated or skipped.
 
-# _fetch_and_cache_tags fetches all possible tags using termux_pkg_auto_update, but using Ninja build system. 
+# _fetch_and_cache_tags fetches all possible tags using neoterm_pkg_auto_update, but using Ninja build system. 
 # The key difference is that we make the process concurrent, allowing us to fetch tags simultaneously rather than one at a time. 
-# Once all tags are cached, the termux_pkg_auto_update function will operate much more quickly. 
-# We avoid packages with overwritten termux_pkg_auto_update to prevent unexpected modifications to the package`s build.sh.
+# Once all tags are cached, the neoterm_pkg_auto_update function will operate much more quickly. 
+# We avoid packages with overwritten neoterm_pkg_auto_update to prevent unexpected modifications to the package`s build.sh.
 _fetch_and_cache_tags() {
 	if [ "$(uname -o)" = "Android" ] || [ -e "/system/bin/app_process" ]; then
 		if ! command -v ninja &> /dev/null; then
@@ -138,40 +138,40 @@ _fetch_and_cache_tags() {
 	
 	if ! command -v ninja &> /dev/null; then
 		echo "INFO: Fetching ninja build system"
-		. "${TERMUX_SCRIPTDIR}"/scripts/build/termux_download.sh
-		. "${TERMUX_SCRIPTDIR}"/scripts/build/setup/termux_setup_ninja.sh
-		TERMUX_ON_DEVICE_BUILD=false TERMUX_COMMON_CACHEDIR=/tmp TERMUX_PKG_TMPDIR=/tmp termux_setup_ninja
+		. "${NEOTERM_SCRIPTDIR}"/scripts/build/neoterm_download.sh
+		. "${NEOTERM_SCRIPTDIR}"/scripts/build/setup/neoterm_setup_ninja.sh
+		NEOTERM_ON_DEVICE_BUILD=false NEOTERM_COMMON_CACHEDIR=/tmp NEOTERM_PKG_TMPDIR=/tmp neoterm_setup_ninja
 	fi
 
 	echo "INFO: Fetching and caching tags"
 
-	# First invocation of termux_repology_api_get_latest_version fetches and caches repology metadata.
-	quiet termux_repology_api_get_latest_version ' '
+	# First invocation of neoterm_repology_api_get_latest_version fetches and caches repology metadata.
+	quiet neoterm_repology_api_get_latest_version ' '
 
     local __PACKAGES=()
-	for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${TERMUX_SCRIPTDIR}/repo.json"); do
+	for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${NEOTERM_SCRIPTDIR}/repo.json"); do
 		for pkg_dir in "${repo_dir}"/*; do
 			! quiet _should_update "${pkg_dir}" && continue # Skip if not needed.
-			grep -q '^termux_pkg_auto_update' "${pkg_dir}/build.sh" && continue # Skip if package has custom auto-update
+			grep -q '^neoterm_pkg_auto_update' "${pkg_dir}/build.sh" && continue # Skip if package has custom auto-update
 			__PACKAGES+=("${pkg_dir}")
 		done
 	done
 
 	__main__() {
-		cd ${TERMUX_SCRIPTDIR}
-		export TERMUX_PKG_NAME="${1##*/}" TERMUX_PKG_BUILDER_DIR=${1}
+		cd ${NEOTERM_SCRIPTDIR}
+		export NEOTERM_PKG_NAME="${1##*/}" NEOTERM_PKG_BUILDER_DIR=${1}
 		set +eu;
 		for i in scripts/updates/{**/,}*.sh "${1}/build.sh"; do source ${i}; done
 		set -eu
-		termux_pkg_upgrade_version() {
-			[[ -n "$1" ]] && echo "PKG|$TERMUX_PKG_NAME|${1#*:}"
+		neoterm_pkg_upgrade_version() {
+			[[ -n "$1" ]] && echo "PKG|$NEOTERM_PKG_NAME|${1#*:}"
 			exit 0
 		}
-		termux_repology_auto_update() {
-			echo "PKG|$TERMUX_PKG_NAME|$(termux_repology_api_get_latest_version "${TERMUX_PKG_NAME}" | sed "s/^null$/${TERMUX_PKG_VERSION#*:}/")"
+		neoterm_repology_auto_update() {
+			echo "PKG|$NEOTERM_PKG_NAME|$(neoterm_repology_api_get_latest_version "${NEOTERM_PKG_NAME}" | sed "s/^null$/${NEOTERM_PKG_VERSION#*:}/")"
 			exit 0
 		}
-		termux_pkg_auto_update
+		neoterm_pkg_auto_update
 	}
 
 	__generate__() {
@@ -183,7 +183,7 @@ _fetch_and_cache_tags() {
 	}
 	
 	local LATEST_TAGS="$(\
-		F="$(declare -p TERMUX_SCRIPTDIR GITHUB_TOKEN TERMUX_REPOLOGY_DATA_FILE); $(declare -f __main__ | sed 's/__main__ ()//')" \
+		F="$(declare -p NEOTERM_SCRIPTDIR GITHUB_TOKEN NEOTERM_REPOLOGY_DATA_FILE); $(declare -f __main__ | sed 's/__main__ ()//')" \
 		env --chdir=/tmp  ninja -f /dev/stdin <<< "$(__generate__)" |& grep "^PKG|"
 	)"
 	
@@ -200,9 +200,9 @@ _check_updated() {
 			set +eu
 			quiet source "${1}/build.sh"
 			set -eu
-			export TERMUX_PKG_UPGRADE_VERSION_DRY_RUN=1
-			if quiet termux_pkg_upgrade_version "${_LATEST_TAGS[${1##*/}]}"; then
-				echo "INFO: Skipping ${1##*/}: already at version ${TERMUX_PKG_VERSION#*:}"
+			export NEOTERM_PKG_UPGRADE_VERSION_DRY_RUN=1
+			if quiet neoterm_pkg_upgrade_version "${_LATEST_TAGS[${1##*/}]}"; then
+				echo "INFO: Skipping ${1##*/}: already at version ${NEOTERM_PKG_VERSION#*:}"
 				return 0
 			fi
 			return 1
@@ -265,11 +265,11 @@ _should_update() {
 
 	if [[ ! -f "${pkg_dir}/build.sh" ]]; then
 		# Fail if detected a non-package directory.
-		termux_error_exit "ERROR: directory '${pkg_dir}' is not a package."
+		neoterm_error_exit "ERROR: directory '${pkg_dir}' is not a package."
 	fi
 
-	if { [[ "${PACKAGES_OPT_OUT:-}" == "true" ]] && grep -q '^TERMUX_PKG_AUTO_UPDATE=false$' "${pkg_dir}/build.sh"; } || \
-			{ [[ "${PACKAGES_OPT_OUT:-}" != "true" ]] && ! grep -q '^TERMUX_PKG_AUTO_UPDATE=true$' "${pkg_dir}/build.sh"; }; then
+	if { [[ "${PACKAGES_OPT_OUT:-}" == "true" ]] && grep -q '^NEOTERM_PKG_AUTO_UPDATE=false$' "${pkg_dir}/build.sh"; } || \
+			{ [[ "${PACKAGES_OPT_OUT:-}" != "true" ]] && ! grep -q '^NEOTERM_PKG_AUTO_UPDATE=true$' "${pkg_dir}/build.sh"; }; then
 		return 1 # Skip.
 	fi
 
@@ -289,26 +289,26 @@ shopt -s extglob
 _update_dependencies() {
 	local pkg_dir="$1"
 
-	if ! grep -qE "^(TERMUX_PKG_DEPENDS|TERMUX_PKG_BUILD_DEPENDS|TERMUX_SUBPKG_DEPENDS)=" \
+	if ! grep -qE "^(NEOTERM_PKG_DEPENDS|NEOTERM_PKG_BUILD_DEPENDS|NEOTERM_SUBPKG_DEPENDS)=" \
 		"${pkg_dir}"/+(build|*.subpackage).sh; then
 		return 0
 	fi
-	# shellcheck disable=SC2086 # Allow splitting of TERMUX_PACKAGES_DIRECTORIES.
+	# shellcheck disable=SC2086 # Allow splitting of NEOTERM_PACKAGES_DIRECTORIES.
 	while read -r dep dep_dir; do
 		if [[ -z $dep ]]; then
 			continue
 		elif [[ "${dep}" == "ERROR" ]]; then
-			termux_error_exit "ERROR: Obtaining update order failed for $(basename "${pkg_dir}")"
+			neoterm_error_exit "ERROR: Obtaining update order failed for $(basename "${pkg_dir}")"
 		fi
 		_should_update "${dep_dir}"  && ! _check_updated "${dep_dir}" && _run_update "${dep_dir}"
-	done <<<"$("${TERMUX_SCRIPTDIR}"/scripts/buildorder.py "${pkg_dir}" $TERMUX_PACKAGES_DIRECTORIES || echo "ERROR")"
+	done <<<"$("${NEOTERM_SCRIPTDIR}"/scripts/buildorder.py "${pkg_dir}" $NEOTERM_PACKAGES_DIRECTORIES || echo "ERROR")"
 }
 
 echo "INFO: Running update for: $*"
 
 if [[ "$1" == "@all" ]]; then
 	_fetch_and_cache_tags
-	for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${TERMUX_SCRIPTDIR}/repo.json"); do
+	for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${NEOTERM_SCRIPTDIR}/repo.json"); do
 		for pkg_dir in "${repo_dir}"/*; do
 			_unix_millis=$(date +%s%N | cut -b1-13)
 			! _should_update "${pkg_dir}" && continue # Skip if not needed.
@@ -322,13 +322,13 @@ if [[ "$1" == "@all" ]]; then
 			# and not care about anything else in between. If something fails to update,
 			# it will be reported by failure handling code, so no worries.
 			_run_update "${pkg_dir}"
-			echo "termux - took $(ms_to_human_readable $(( $(date +%s%N | cut -b1-13) - _unix_millis )))"
+			echo "neoterm - took $(ms_to_human_readable $(( $(date +%s%N | cut -b1-13) - _unix_millis )))"
 		done
 	done
 else
 	for pkg in "$@"; do
 		if [ ! -d "${pkg}" ]; then # If only package name is given, try to find it's directory.
-			for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${TERMUX_SCRIPTDIR}/repo.json"); do
+			for repo_dir in $(jq --raw-output 'del(.pkg_format) | keys | .[]' "${NEOTERM_SCRIPTDIR}/repo.json"); do
 				if [ -d "${repo_dir}/${pkg}" ]; then
 					pkg="${repo_dir}/${pkg}"
 					break
@@ -353,8 +353,8 @@ _gh_create_new_issue() {
 	local body
 	local link
 
-	if [[ "${assignee:-termuxbot2}" == "termuxbot2" ]]; then
-		assignee="MrAdityaAlok" # Assign myself if termuxbot2 is the actor.
+	if [[ "${assignee:-neotermbot2}" == "neotermbot2" ]]; then
+		assignee="MrAdityaAlok" # Assign myself if neotermbot2 is the actor.
 	fi
 	
 	# Extract origin URL, commit hash and builder directory and put everything together
@@ -362,9 +362,9 @@ _gh_create_new_issue() {
 
 	body="$(
 		cat <<-EOF
-			Hi, I'm Termux 🤖.
+			Hi, I'm NeoTerm 🤖.
 
-			I'm here to help you update your Termux packages.
+			I'm here to help you update your NeoTerm packages.
 
 			I've tried to update the [${pkg_name}](${link}) package, but it failed.
 
